use Mix.Config

# Configure your database
config :oauth_gateway, OauthGateway.Repo,
  username: "postgres",
  password: "postgres",
  database: "oauth_gateway_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :oauth_gateway_web, OauthGatewayWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../apps/oauth_gateway_web/assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :oauth_gateway_web, OauthGatewayWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/oauth_gateway_web/(live|views)/.*(ex)$",
      ~r"lib/oauth_gateway_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# GitHub ID
config :ueberauth, Ueberauth.Strategy.Github.OAuth,
  client_id: System.get_env("GITHUB_CLIENT_ID") || "32203a63788e8b0389df",
  client_secret:
    System.get_env("GITHUB_CLIENT_SECRET") || "618149a9599926bd8fcd5ef19805ecb5fab18323"

# Feishu ID
config :ueberauth, Ueberauth.Strategy.Feishu.OAuth,
  client_id: System.get_env("FEISHU_CLIENT_ID") || "cli_9d7f455d37765102",
  client_secret: System.get_env("FEISHU_CLIENT_SECRET") || "7Zls6vIlku5dtQV8mF7GOgzXAdLDrDEl"
